package com.gene42.commons.utils.files;

import java.io.File;
import java.io.IOException;

import org.jetbrains.annotations.NotNull;

/**
 * Temp file which deletes itself when closed, or on jvm exit. It's based on {@link CloseableTempDir}.
 * The temp file is created in a temp dir generated by the super class.
 *
 * @version $Id$
 */
public class CloseableTempFile extends CloseableTempDir {
    private final File file;

    /**
     * Create a temp file with a random name.
     * @throws IOException if any issue occurs while creating the temp file
     */
    public CloseableTempFile() throws IOException {
        this(getRandomName());
    }

    /**
     * Create a temp file with the given name.
     * @param fileName the name to give the temporary file
     * @throws IOException if any issue occurs while creating the temp file
     */
    public CloseableTempFile(@NotNull String fileName) throws IOException {
        super();
        this.file = new File(this.getDir(), fileName);
    }

    /**
     * Get the temp file.
     * @return the temp File
     */
    @NotNull
    public File getFile() {
        return this.file;
    }
}
